[project]
name = "hh-autoapply"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "playwright>=1.57.0",
    "pydantic-ai>=1.31.0",
    "pydantic-settings>=2.12.0",
    "tortoise-orm>=0.25.1",
]

[tool.pyright]
venvPath = '.'
venv = '.venv'
