[project]
name = "hh-autoapply"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
oauth = [ "aiohttp" ]
worker = [ "PyYAML", "httpx", "pydantic_ai", "tortoise-orm" ]

[tool.pyright]
venvPath = '.'
venv = '.venv'
